name: Commit Streak Tracker

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'  # Once a day at midnight UTC
  push:
    branches:
      - main  # Runs on pushes to the main branch, but we will check if a commit is needed.

jobs:
  streak:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Calculate commit streak
        run: |
          # Get the last commit date
          LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=short)
          echo "Last Commit Date: $LAST_COMMIT_DATE"

          # Read the previous streak from the file
          if [[ -f streak.txt ]]; then
            STREAK=$(cat streak.txt)
          else
            STREAK=0
          fi

          # Compare with the current date
          TODAY=$(date +%Y-%m-%d)
          PREVIOUS_DAY=$(date -d "$LAST_COMMIT_DATE" +%Y-%m-%d)

          # If already committed today, skip
          if [[ "$TODAY" == "$PREVIOUS_DAY" ]]; then
            echo "Already committed today. Streak remains: $STREAK"
            exit 0  # Exit early, no need to continue with the commit
          else
            if [[ "$TODAY" > "$PREVIOUS_DAY" ]]; then
              STREAK=$((STREAK + 1))
              echo "Streak increased to: $STREAK"
            else
              STREAK=1
              echo "New streak started. Streak: $STREAK"
            fi
          fi

          # Save the streak count
          echo "$STREAK" > streak.txt
          
      - name: Commit changes if streak updated
        run: |
          # Only commit if the streak file was modified
          git config --global user.email "raghavahuja2801@gmail.com"
          git config --global user.name "Raghav Ahuja"
          git add streak.txt
          git commit -m "Update commit streak" || echo "No changes to commit"
          git push
        # This step runs only if there are changes to commit
      - name: Update the README with streak badge
        run: |
          # Read the streak count from streak.txt
          STREAK=$(cat streak.txt)

          # Update README to include the current streak in the badge URL
          echo "current streak: $STREAK"
          sed -i "s|!\\[Commit Streak\\](https://img.shields.io/badge/Commit%20Streak-[0-9]*-brightgreen\\?style=for-the-badge\\&labelColor=333333\\&color=00C851\\&label=Streak)|![Commit Streak](https://img.shields.io/badge/Commit%20Streak-${STREAK}-brightgreen?style=for-the-badge&labelColor=333333&color=00C851&label=Streak)|" README.md
           # Log changes and check if README was updated
          cat README.md
          git diff README.md || echo "No changes detected"
          # Commit and push the updated README
          git add README.md
          git commit -m "Update commit streak badge in README" || echo "No changes to commit"
          git push
